[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "langchain-core>=0.3.51",
    "mcp[cli]>=1.6.0",
    "requests>=2.32.3",
]
